spring.application.name=url-shortener

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
app.base-url=${BASE_URL}

spring.jpa.hibernate.ddl-auto=update


